# Generated by Django 4.1.3 on 2022-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
